PhotoManager/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Helpers;
using PhotoManager.DAL.Entities;
using PhotoManager.Helpers.Attributes;
using PhotoManager.Model.ViewModels;
using PhotoManager.Model.ViewModels.Mapping;
using Services;
using Services.Interfaces;

namespace PhotoManager.Controllers
{
    [AppAuthorize]
    public class AlbumController:Controller
    {
        private readonly IUserService _userService;
        private readonly IAlbumManagementService _albumManagementService;
        private readonly IPhotoManagementService _photoManagementService;
        private readonly IAlbumGetInfoService _albumGetInfoService;
        private readonly IPhotoGetInfoService _photoGetInfoService;

        private readonly IAdvancedMapper _advancedMapper;
        private readonly int _objectsPerPages;
        private readonly int _objectsPerRow;

        public AlbumController(IUserService userService, IAlbumGetInfoService albumGetInfoService, IPhotoGetInfoService photoGetInfoService,
            IAdvancedMapper advancedMapper, IAlbumManagementService albumManagementService, IPhotoManagementService photoManagementService)
        {
            _userService = userService;
            _albumGetInfoService = albumGetInfoService;
            _photoGetInfoService = photoGetInfoService;
            _advancedMapper = advancedMapper;
            _albumManagementService = albumManagementService;
            _photoManagementService = photoManagementService;
            _objectsPerPages = 20;
            _objectsPerRow = 5;
            ViewBag.ObjectsPerRow = _objectsPerRow;
        }

        //[HttpGet]
        //public ActionResult AlbumsEdit(int page = 1)
        //{
        //    var pagedAlbumViewModels = _albumGetInfoService
        //        .GetAlbumsByUserName(User.Identity.Name, _objectsPerPages, page)
        //        .Select(a=>_advancedMapper.MapAlbum(a, ImageSize.Small))
        //        .ToList();

        //    var albumViewModelIds = _albumGetInfoService.GetAllAlbumsId(User.Identity.Name).ToList();

        //    var ilvm=new ItemListViewModel<AlbumViewModel>(pagedAlbumViewModels, albumViewModelIds, new PageInfo(page,_objectsPerPages, albumViewModelIds.Count()));

        //    return View(ilvm);
        //}

        //[HttpGet]
        //public ActionResult AddExistingPhotosToAnotherAlbum(int albumId, int page = 1)
        //{
        //    var photos = _photoGetInfoService.GetAllPhotos(u=>u.Username==User.Identity.Name,a=>a.AlbumId!=albumId,_objectsPerPages,page);

        //    ItemListViewModel<PhotoViewModel> ilvm = new ItemListViewModel<PhotoViewModel>();
        //    if (!photos.Any())
        //    {
        //        ModelState.AddModelError("", "There are no existing photos that you can add.");
        //        return View(ilvm);
        //    }

        //    var albumName = _albumGetInfoService.GetAlbumNameById(albumId);

        //    var pagedPhotoViewModels = photos.Select(q => _advancedMapper.MapPhoto(q, ImageSize.Small, albumId, albumName)).ToList();

        //    var photoViewModelIds = _photoGetInfoService.GetAllPhotosId(u=>u.Username==User.Identity.Name, a=>a.AlbumId!=albumId).ToList();

        //    ilvm = new ItemListViewModel<PhotoViewModel>(pagedPhotoViewModels, photoViewModelIds, new PageInfo(page, _objectsPerPages, photoViewModelIds.Count()));
        //    return View(ilvm);
        //}

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddExistingPhotosToAnotherAlbum(int albumId, int[] itemsToAdd)
        {
            if (itemsToAdd == null)
            {
                ModelState.AddModelError("", "You didn`t choose any photo!");
                return View("AddExistingPhotosToAnotherAlbum");
            }

            if (!_userService.IsOwner(User.Identity.Name,albumId,itemsToAdd.First()))
            {
                return View("EnterForeignAccount");
            }

            foreach (var photoId in itemsToAdd)
            {
                _photoManagementService.CreatePhoto(photoId, albumId, User.Identity.Name);
            }

            return RedirectToAction("AlbumEdit", "Photo",new { albumId = albumId });
        }

        [HttpGet]
        public ActionResult UpdateAlbum(int albumId)
        {
            if (!_userService.IsOwner(User.Identity.Name,albumId))
            {
                return View("EnterForeignAccount");
            }

            Album album = _albumGetInfoService.GetAlbumById(albumId, User.Identity.Name);

            var albumViewModel = _advancedMapper.MapAlbum(album, ImageSize.Medium);
            return View(albumViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UpdateAlbum(AlbumViewModel albumViewModel)
        {
            if (!_userService.IsOwner(User.Identity.Name,albumViewModel.AlbumId))
            {
                return View("EnterForeignAccount");
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "You have inputed wrong data. Please, try again");
                return View(albumViewModel);
            }
            Album album = _advancedMapper.MapAlbumViewModel(albumViewModel);
            _albumManagementService.UpdateAlbum(album);
            return RedirectToAction("AlbumsOverview");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult RemoveAlbums(int[] itemsToDelete)
        {
            if (itemsToDelete == null)
            {
                ModelState.AddModelError("", "You didn`t choose any album!");
                return View("AlbumsEdit");
            }

            if (!_userService.IsOwner(User.Identity.Name,itemsToDelete.First()))
            {
                return View("EnterForeignAccount");
            }

            foreach (var id in itemsToDelete)
            {
                _albumManagementService.DeleteAlbum(id);
            }

            if (!_userService.AnyUserAlbums(User.Identity.Name))
            {
                return View("NoAlbums");
            }
            return RedirectToAction("AlbumsEdit");
        }

        [HttpGet]
        public ActionResult CreateAlbum()
        {
            var username = User.Identity.Name;
            User user = _userService.GetUserByName(username);
            AlbumViewModel albumViewModel = new AlbumViewModel();
            albumViewModel.UserId = user.UserId;
            return View(albumViewModel);
        }

        [HttpPost]
        public ActionResult CreateAlbum(AlbumViewModel albumViewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "You have inputed the wrong data. Please try again!");
                return View(albumViewModel);
            }

            Album album = _albumGetInfoService.GetAlbumByName(User.Identity.Name,albumViewModel.Name);

            if (album == null)
            {
                album = _advancedMapper.MapAlbumViewModel(albumViewModel);
                _albumManagementService.CreateAlbum(album, User.Identity.Name);
            }
            else
            {
                ModelState.AddModelError("", "The album with such name already exists!");
                return View(albumViewModel);
            }

            return RedirectToAction("AlbumOverview","Photo", new { albumId = album.AlbumId });
        }

        [HttpGet]
        public ActionResult AlbumsOverview(int page = 1)
        {
            if (!_userService.AnyUserAlbums(User.Identity.Name))
            {
                return View("NoAlbums");
            }

            var pagedAlbumViewModels = _albumGetInfoService
                .GetAlbumsByUserName(User.Identity.Name, _objectsPerPages, page)
                .Select(a => _advancedMapper.MapAlbum(a, ImageSize.Small))
                .ToList();

            var albumViewModelIds = _albumGetInfoService.GetAllAlbumsId(User.Identity.Name).ToList();

            var ilvm = new ItemListViewModel<AlbumViewModel>(pagedAlbumViewModels, new PageInfo(page, _objectsPerPages, 50));
            return View(ilvm);
        }
    }
}

PhotoManager/Views/Photo/AlbumEdit.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model ItemListViewModel<PhotoViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Photos edit</h3>
@if (Model == null)
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
}
else
{
    <div class="container div-padding">
        <div class="row">
            @Html.Partial("_ListPhotosEditPartial", Model.ViewModels)
        </div>
    </div>
    if (Model.PageInfo.TotalPages > 1 && Model != null)
    {
        <div class="btn-group div-centercontent">
            @Html.PageLinks(Model.PageInfo, x => Url.Action("AlbumEdit", new { albumId = Model.ViewModels.First().AlbumId, page = x }))
        </div>
    }

}




PhotoManager/Views/Photo/AlbumOverview.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model ItemListViewModel<PhotoViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Photos overview</h3>
<div class="container div-padding">
    <div class="row">
        <div class="col-md-10">
            @Html.Partial("_ListPhotosPartial", Model)
        </div>
        <div class="col-md-2">
            @Html.ActionLink("Edit mode", "AlbumEdit", "Photo", new {albumId = Model.ViewModels.First().AlbumId}, new {@class = "btn btn-default"})
            @Html.Label("Public link to this album:")
            @{
                string href = "http://localhost:59136/Photo/PublicAlbumOverview?name=" + @Model.ViewModels.First().AlbumName;
            }
            @Html.ActionLink(href, "PublicAlbumOverview", new {name = Model.ViewModels.First().AlbumName}) 
        </div>
    </div>
</div>

@if (Model.PageInfo.TotalPages > 1)
{
    <div class="btn-group div-centercontent">
        @Html.PageLinks(Model.PageInfo, x => Url.Action("AlbumOverview", new { albumId= Model.ViewModels.First().AlbumId, page = x }))
    </div>
}

PhotoManager/Views/Photo/NoAlbum.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Such album doesn`t exist.</h2>

PhotoManager/Views/Photo/NoPhotos.cshtml
@using PhotoManager.Model.ViewModels
@model int
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2> You don`t have any photos yet!</h2>
@Html.ActionLink("Add new photo", "PhotoUpload", "Photo", new { albumId = Model }, new { @class = "btn btn-default label-block" })
@if (ViewBag.PhotosCount != 0)
{
    @Html.ActionLink("Add existing photo", "AddExistingPhotosToAnotherAlbum", "Album", new { albumId = Model }, new { @class = "btn btn-default label-block" })
}

PhotoManager/Views/Photo/PhotoSlider.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model PhotoSliderViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="new-div">
    @Html.ActionLink("Previous", "PhotoSlider", "Photo", new { albumId=Model.ActivePhoto.AlbumId, itemPosition=Model.PreviousPhoto.ItemPosition }, new { @class = "btn btn-default" })
    @Html.ActionLink("Next", "PhotoSlider", "Photo", new { albumId = Model.ActivePhoto.AlbumId, itemPosition=Model.NextPhoto.ItemPosition }, new { @class = "btn btn-default" })


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="form-group form-horizontal row">
            <div class="col col-xs-10 col-md-10">
                @Html.Image(Model.ActivePhoto.FilePath, Model.ActivePhoto.Description, new { @class = "img-thumbnail" })
            </div>
            <div class="col">
                @if (Model.ActivePhoto.Description != String.Empty)
                {
                    <div>
                        @Html.LabelFor(model => model.ActivePhoto.Description, htmlAttributes: new { @class = "control-label" })
                        @Html.Label(Model.ActivePhoto.Description, htmlAttributes: new { @class = "label-value" })
                    </div>
                }
                @if (Model.ActivePhoto.PhotoTakingPlace != String.Empty)
                {
                    <div>
                        @Html.LabelFor(model => model.ActivePhoto.PhotoTakingPlace, htmlAttributes: new { @class = "control-label" })
                        @Html.Label(Model.ActivePhoto.PhotoTakingPlace, htmlAttributes: new { @class = "label-value" })
                    </div>
                }
                @if (Model.ActivePhoto.CameraModel != String.Empty)
                {
                    <div>
                        @Html.LabelFor(model => model.ActivePhoto.CameraModel, htmlAttributes: new { @class = "control-label" })
                        @Html.Label(Model.ActivePhoto.CameraModel, htmlAttributes: new { @class = "label-value" })
                    </div>
                }
                <div>
                    @if (!Model.ActivePhoto.Diaphragm.Contains("0"))
                    {
                        @Html.LabelFor(model => model.ActivePhoto.Diaphragm, htmlAttributes: new { @class = "control-label" })
                        @Html.Label(Model.ActivePhoto.Diaphragm.ToString(), htmlAttributes: new { @class = "label-value" })
                    }
                </div>
                <div>
                    @Html.LabelFor(model => model.ActivePhoto.Flash, htmlAttributes: new { @class = "control-label" })
                    @Html.Label(Model.ActivePhoto.Flash.ToString(), htmlAttributes: new { @class = "label-value" })
                </div>
                <div>
                    @Html.LabelFor(model => model.ActivePhoto.ISO, htmlAttributes: new { @class = "control-label" })
                    @Html.Label(Model.ActivePhoto.ISO.ToString(), htmlAttributes: new { @class = "label-value" })
                </div>
                <div>
                    @Html.LabelFor(model => model.ActivePhoto.LensFocalLength, htmlAttributes: new { @class = "control-label" })
                    @Html.Label(Model.ActivePhoto.LensFocalLength.ToString(), htmlAttributes: new { @class = "label-value" })
                </div>
                <div>
                    @{
                        string shutterSpeed = String.Empty;
                        var shutterSpeedValue = Model.ActivePhoto.ShutterSpeed;
                        if (shutterSpeedValue.Numerator != 0 && shutterSpeedValue.Denominator != 0)
                        {
                            Html.Label("Shutter speed (in sec): ", htmlAttributes: new { @class = "control-label" });

                            if (shutterSpeedValue.Denominator == 1)
                            {
                                shutterSpeed = shutterSpeedValue.Numerator.ToString();
                            }
                            else
                            {
                                shutterSpeed = String.Concat(shutterSpeedValue.Numerator.ToString(), "/", shutterSpeedValue.Denominator.ToString());
                            }
                            @Html.Label("Shutter speed (in sec): ", htmlAttributes: new { @class = "control-label" })
                            @Html.Label(shutterSpeed, htmlAttributes: new { @class = "label-value" })
                        }
                    }

                </div>

            </div>
            <div class="form-group">
                @if (ViewBag.IsOwner==true)
                {
                    @Html.ActionLink("Edit Mode", "UpdatePhoto", "Photo", new {id = Model.ActivePhoto.PhotoId}, new {@class = "btn btn-default"})
                }
            </div>
        </div>
    </div>
</div>

PhotoManager/Views/Photo/PhotoUpload.cshtml
@model PhotoManager.Model.ViewModels.FilesViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Photo upload</h3>
<div class="new-div">
@using (Html.BeginForm("PhotoUpload", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Label("Upload Image")
    <input type="file" name="files.Files" class="form-control-file custom-file-input" multiple id="file"/>
    @Html.Hidden("files.AlbumId", Model.AlbumId)
    <input type="submit" value="Upload" /> 
}
</div>

PhotoManager/Views/Photo/PublicAlbumOverview.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model ItemListViewModel<PhotoViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Public photos overview</h3>

@Html.Partial("_ListPhotosPartial", Model)

@if (Model.PageInfo.TotalPages > 1)
{
    <div class="btn-group div-centercontent">
        @Html.PageLinks(Model.PageInfo, x => Url.Action("PublicAlbumOverview", new { name=Model.ViewModels.First().Name, page = x }))
    </div>
}

PhotoManager/Views/Photo/UpdatePhoto.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@model PhotoManager.Model.ViewModels.PhotoViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Update photo</h3>

<div class="container div-wide new-div">
    <div class="col-md-7">
        @Html.Image(Model.FilePath, Model.Name, new { @class = "img-thumbnail" })
    </div>
    <div class="col-md-5">
        @using (Html.BeginForm("UpdatePhoto", "Photo", FormMethod.Post, null))
        {
            @Html.AntiForgeryToken();
            @Html.ValidationSummary(true, "", new { @class = "text-danger" });
            @Html.HiddenFor(m => m.PhotoId);
            @Html.HiddenFor(m => m.UpdateDateTime);
            @Html.HiddenFor(m => m.Name);
            @Html.HiddenFor(m => m.FilePath);
            @Html.HiddenFor(m => m.OriginalName);
            @Html.Partial("_FormPhoto",Model)
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save all changes" class="btn btn-default" />
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @using (Html.BeginForm("RemovePhotos", "Photo", FormMethod.Post))
            {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("itemsToDelete", Model.PhotoId)
                    <input type="submit" value="Delete photo" class="btn btn-default" />
                }
            </div>
        </div>
    </div>
</div>

PhotoManager/Views/Photo/_ListPhotosEditPartial.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model List<PhotoViewModel>

@using (Html.BeginForm("RemovePhotos", "Photo", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    <div class="col-md-10">
        @for (int j = 0; j < Model.Count;)
        {
            <div class="row">
                @for (int i = 0; i < ViewBag.ObjectsPerRow && j < Model.Count; i++)
                {
                    var viewModel = Model[j];

                    <div class="col-md-2">
                        <figure class="figure">
                            @Html.Image(viewModel.FilePath, viewModel.Name, null)
                            <div class="form-group">
                                <input type="checkbox" name="itemsToDelete" value="@viewModel.PhotoId"/>
                                @Html.ActionLink(" ", "UpdatePhoto", "Photo", new {id = viewModel.PhotoId}, new {@class = "glyphicon glyphicon-pencil"})
                            </div>
                            <div class="form-group col-md-9 div-narrow" style="padding-left: 0">
                                <figcaption class="figure-caption caption-label">@viewModel.Description</figcaption>
                                <figcaption class="figure-caption caption-label">@viewModel.PhotoTakingPlace</figcaption>
                            </div>
                        </figure>
                    </div>
                    j++;
                }
            </div>
        }
    </div>
    <div class="col-md-2">
        @Html.ActionLink("Overview Mode", "AlbumOverview", "Photo", new { albumId = Model.First().Albums.First().AlbumId }, new { @class = "btn btn-default" })
        @Html.ActionLink("Add new photo(s)", "PhotoUpload", "Photo", new { albumId = Model.First().Albums.First().AlbumId }, new { @class = "btn btn-default" })
        @if (ViewBag.PhotosCount != 0)
        {
            @Html.ActionLink("Add existing photo", "AddExistingPhotosToAnotherAlbum", "Album", new { albumId = Model.First().Albums.First().AlbumId }, new { @class = "btn btn-default" })
        }
        <input type="submit" value="Delete photo(s)" class="btn btn-default" />
    </div>
}

PhotoManager/Views/Photo/_ListPhotosPartial.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model ItemListViewModel<PhotoViewModel>

<div class="album py-5 bg-light">
<div class="container">
    
    @for (int j = 0; j < Model.ViewModels.Count;)
    {
        <div class="row">
            @for (int i = 0; i < ViewBag.ObjectsPerRow && j < Model.ViewModels.Count; i++)
            {
                var viewModel = Model.ViewModels[j];

                <div class="col-md-2">
                        @Html.ImageLink(viewModel.FilePath, viewModel.Name, "PhotoSlider", "Photo", new {albumId=viewModel.AlbumId, itemPosition =viewModel.ItemPosition},null,null)
                        <div class="form-group col-md-9 div-narrow" style="padding-left: 0">
                                <figcaption class="figure-caption caption-label label-block">@viewModel.Description</figcaption>
                                <figcaption class="figure-caption caption-label label-block">@viewModel.PhotoTakingPlace</figcaption>
                    </div>
                </div>
                j++;
            }
        </div>
          }
   
</div>
</div>