PhotoManager/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Helpers;
using PhotoManager.Model.ViewModels;
using PhotoManager.Model.ViewModels.Mapping;
using Services.Interfaces;

namespace PhotoManager.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPhotoGetInfoService _photoGetInfoService;

        private readonly IAdvancedMapper _advancedMapper;

        private readonly List<string> _diaphragmList;
        private readonly int _objectsPerPages;
        private readonly int _objectsPerRow;

        public SearchController(IPhotoGetInfoService photoGetInfoService, IAdvancedMapper advancedMapper)
        {
            _advancedMapper = advancedMapper;
            _photoGetInfoService = photoGetInfoService;
            _diaphragmList = new List<string> {"diaphragm","f/1.4", "f/2", "f/2.8", "f/4", "f/5.6", "f/8", "f/11", "f/16", "f/22"};
            _objectsPerPages = 20;
            _objectsPerRow = 5;
            ViewBag.ObjectsPerRow = _objectsPerRow;
        }

        [HttpGet]
        public ActionResult ForAdvancedSearch()
        {
            var photoViewModel = new PhotoViewModel();
            ViewBag.DiaphragmList = _diaphragmList;
            return View(photoViewModel);
        }

        //[HttpGet]
        //public ActionResult AdvancedSearch(PhotoViewModel photoViewModel, int page = 1)//searchQuery
        //{
        //    ViewBag.SearchViewModel = photoViewModel;
        //    var photo = _advancedMapper.MapPhotoViewModel(photoViewModel);
        //    var pagedPhotoViewModels = _photoGetInfoService.AdvancedSearchPhotos(photo,page,_objectsPerPages)
        //        .Select(q => _advancedMapper.MapPhoto(q, ImageSize.Small)).ToList();

        //    var photoViewModelIds =_photoGetInfoService.AdvancedSearchPhotosIds(photo).ToList();

        //    var ilvm = new ItemListViewModel<PhotoViewModel>(pagedPhotoViewModels, photoViewModelIds, new PageInfo(page, _objectsPerPages, photoViewModelIds.Count()));

        //    ViewBag.DiaphragmList = _diaphragmList;

        //    return View("AdvancedSearchResult", ilvm);
        //}

        //[HttpGet]
        //public ActionResult SearchResult(string searchQuery, int page = 1)
        //{
        //    ViewBag.SearchQuery = searchQuery;
        //    var pagedPhotoViewModels = new List<PhotoViewModel>();
        //    var photoViewModelIds = _photoGetInfoService.FindPhotosIdsByDescriptionQuery(searchQuery);
        //    if (!String.IsNullOrEmpty(searchQuery))
        //    {
        //        pagedPhotoViewModels = _photoGetInfoService.FindPhotosByDescriptionQuery(searchQuery,page, _objectsPerPages)
        //            .Select(q => _advancedMapper.MapPhoto(q, ImageSize.Small)).ToList();
        //    }

        //    var ilvm = new ItemListViewModel<PhotoViewModel>(pagedPhotoViewModels, photoViewModelIds, new PageInfo(page, _objectsPerPages, photoViewModelIds.Count()));

        //    ViewBag.DiaphragmList = _diaphragmList;

        //    return View(ilvm);
        //}
    }
}

PhotoManager/Views/Search/AdvancedSearchResult.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model ItemListViewModel<PhotoViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="width: 1400px" class="container">
    <div class="form-group">
        <div class="col-md-2">
            <ul class="nav navbar-left">
                <li>@Html.Partial("_ForAdvancedSearch", (PhotoViewModel)ViewBag.SearchViewModel)</li>
            </ul>
        </div>
        <div>
            <h3>Result of advanced search (photos)</h3>

            <div>
                @for (int j = 0; j < Model.ViewModels.Count;)
                {
                    <div class="row">
                        @for (int i = 0; i < ViewBag.ObjectsPerRow && j < Model.ViewModels.Count; i++)
                        {
                            var viewModel = Model.ViewModels[j];

                            <div class="col-md-2">
                                @Html.ImageLink(viewModel.FilePath, viewModel.Name, "PhotoSlider", "Photo", new {photosId = Json.Encode(Model.FullListViewModelIds), photoId = viewModel.PhotoId},null,null)
                                <div class="form-group col-md-9 div-narrow" style="padding-left: 0">
                                    <figcaption class="figure-caption caption-label label-block">@viewModel.Description</figcaption>
                                    <figcaption class="figure-caption caption-label label-block">@viewModel.PhotoTakingPlace</figcaption>
                                </div>
                            </div>
                            j++;
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@if (Model.PageInfo.TotalPages > 1)
{
    for (int i = 1; i <= Model.PageInfo.TotalPages; i++)
    {
        <div class="btn-group">
            @using (Html.BeginForm("AdvancedSearch", "Search", FormMethod.Get))
            {
                <input type="hidden" name="searchViewModel.PhotoTakingPlace" value="@ViewBag.SearchQuery.PhotoTakingPlace" />
                <input type="hidden" name="searchViewModel.Description" value="@ViewBag.SearchQuery.Description" />
                <input type="hidden" name="searchViewModel.CameraModel" value="@ViewBag.SearchQuery.CameraModel" />
                <input type="hidden" name="searchViewModel.Flash" value="@ViewBag.SearchQuery.Flash" />
                <input type="hidden" name="searchViewModel.LensFocalLength" value="@ViewBag.SearchQuery.LensFocalLength" />
                <input type="hidden" name="searchViewModel.ISO" value="@ViewBag.SearchQuery.ISO" />
                <input type="hidden" name="searchViewModel.ShutterSpeed" value="@ViewBag.SearchQuery.ShutterSpeed" />
                <input type="hidden" name="searchViewModel.Diaphragm" value="@ViewBag.SearchQuery.Diaphragm" />
                <input type="hidden" name="page" value="@i" />
                if (Model.PageInfo.PageNumber == i)
                {
                    <input type="submit" value="@i" class="btn btn-primary selected" />
                }
                else
                {
                    <input type="submit" class="btn btn-default" value="@i" />
                }

            }

        </div>
    }
}

PhotoManager/Views/Search/ForAdvancedSearch.cshtml
@model PhotoManager.Model.ViewModels.PhotoViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ForAdvancedSearch",Model)

PhotoManager/Views/Search/SearchResult.cshtml
@using PhotoManager.Helpers.HtmlHelpers
@using PhotoManager.Model.ViewModels
@model ItemListViewModel<PhotoViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Result of search (photos)</h3>
<div class="new-div">
    @for (int j = 0; j < Model.ViewModels.Count;)
    {
        <div class="row">
            @for (int i = 0; i < ViewBag.ObjectsPerRow && j < Model.ViewModels.Count; i++)
            {
                var viewModel = Model.ViewModels[j];

                <div class="col-md-2">
                    @Html.ImageLink(viewModel.FilePath, viewModel.Name, "PhotoSlider", "Photo", new {photosId = Json.Encode(Model.FullListViewModelIds), photoId = viewModel.PhotoId},null,null)
                    <div class="form-group col-md-9 div-narrow" style="padding-left: 0">
                        <figcaption class="figure-caption caption-label label-block">@viewModel.Description</figcaption>
                        <figcaption class="figure-caption caption-label label-block">@viewModel.PhotoTakingPlace</figcaption>
                    </div>
                </div>
                j++;
            }
        </div>
    }
</div>


@if (Model.PageInfo.TotalPages > 1)
{
    for (int i = 1; i <= Model.PageInfo.TotalPages; i++)
    {
        <div class="btn-group">
            @using (Html.BeginForm("SearchResult", "Search", FormMethod.Get))
            {

                @Html.Hidden("searchQuery", (string) ViewBag.SearchQuery)
                <input type="hidden"name="page" value="@i"/>
                if (Model.PageInfo.PageNumber == i)
                {
                    <input type="submit" value="@i"class="btn btn-primary selected"/>
                }
                else
                {
                    <input type="submit" class="btn btn-default" value="@i"/>
                }

            }

        </div>
    }
}